# Generated by Django 4.1.7 on 2023-03-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='My_first_projects',
            new_name='Project',
        ),
    ]
